databases:
  - name: autoswift-backend
    databaseName: autoswift-backend
    user: autoswift-backend

services:
  - type: web
    name: autoswift-backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autoswift-backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false